[api_servers]
api01 ansible_host=10.226.206.130

[payment_servers]
payments01 ansible_host=10.226.206.35

[log_servers]
logs01 ansible_host=10.226.206.85

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/liz/.ssh/id_ed25519
